### ISSUE TITLE
Cannot open database because the directory does not exist

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#128]
* File: backup/mail-backup.db
* Windows
* Happens immediately after first setup, when opening a few mails. Then goes away.

Possible causes:
* `await SQLSourceEMail.save(this);` in `EMail.save()`
* Speculation: `IMAPFolder.downloadMessages()` saves correctly, but `IMAPEMail.download()` does not
* Speculation: Race between the above 2 functions

**Comment by benbucksch** [comment]
As seen by Elena @raffikastudio :

```
index-ogBq-r3Y.js:232409 Error {
  "id": 174,
  "success": false,
  "message": "Cannot open database because the directory does not exist",
  "backendStack": "TypeError: Cannot open database because the directory does not exist\n    at new Database (C:\\Users\\Elena\\AppData\\Local\\Programs\\parula\\resources\\app.asar\\node_modules\\better-sqlite3\\lib\\database.js:65:9)\n    at new Database (C:\\Users\\Elena\\AppData\\Local\\Programs\\parula\\resources\\app.asar\\out\\main\\index.js:124716:5)\n    at getSQLiteDatabase (C:\\Users\\Elena\\AppData\\Local\\Programs\\parula\\resources\\app.asar\\out\\main\\index.js:136759:10)\n    at JPCWebSocket.callListener (C:\\Users\\Elena\\AppData\\Local\\Programs\\parula\\resources\\app.asar\\out\\main\\index.js:35593:18)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async WSCall._incomingMessage (C:\\Users\\Elena\\AppData\\Local\\Programs\\parula\\resources\\app.asar\\out\\main\\index.js:35178:20)\n    at async WebSocket.<anonymous> (C:\\Users\\Elena\\AppData\\Local\\Programs\\parula\\resources\\app.asar\\out\\main\\index.js:35272:9)",
  "originalCall": {
    "id": 174,
    "path": "call",
    "arg": {
      "obj": "17143693227985522688",
      "args": [
        "backup/mail-backup.db"
      ]
    }
  }
}
```

**Comment by jermy-c** [comment]
On MacOS:

- There's a directory created at `/Users/username/Library/Mustang/backup` with no files in it
- There's a directory created at `/Users/username/Library/Application Support/Mustang` with `calendar.db` and other `.db` files

**Comment by benbucksch** [comment]
Does anybody still see this?
