### ISSUE TITLE
MailZIP: Invalid filename

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#133]
<img width="531" alt="圖片" src="https://github.com/user-attachments/assets/fe03c91c-e103-4c59-ae95-5e9af9f99bcd">
<img width="890" alt="圖片" src="https://github.com/user-attachments/assets/8f698d97-2b0f-43b6-b810-9960285f5b59">

**Reproduction**

1. Start the app
2. Go to Mail
3. Click a folder and wait for it to load
4. Click on an email for the first time after loading the folder

**Actual Result**

1. Shows error in console
2. There's a little bit of delay before displaying/loading the email content compared to the ones without

**Expected Result**

1. No Errors
2. No delay when displaying the email content

OS: Mac OS X

**Comment by jermy-c** [comment]
From my investigation:

- Seems likes there's no file path on first load
- The emails take some to download and create the `ZIP`, thus the it's not there causing the error.

Maybe we don't need to fix this because if the backend gets faster and improved we won't have this error.

**Comment by benbucksch** [comment]
Error: ADM-ZIP: Invalid filename
    at Object.INVALID_FILENAME (node_modules\adm-zip\util\errors.js:56:16)
    at new module.exports (node_modules\adm-zip\adm-zip.js:62:32)
    at newAdmZIP (index.js:107144:10)
    at JPCWebSocket.callListener (index.js:35846:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WSCall._incomingMessage (index.js:35431:20)
    at async WebSocket.<anonymous> (index.js:35525:9)

**Comment by benbucksch** [comment]
Blocks #60

**Comment by benbucksch** [comment]
We found that the exception is expected when the file does not exist yet. We handle it.

The error logging was unnecessary. I removed it in git commit 578130b5.

Nick had the idea of moving that logic of creating the file into the backend. I like that. We should do that as well.
