### ISSUE TITLE
After delete message: Invalid UIDset

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#187]
Reproduction:
* Delete the newest message in the inbox

Actual result:
* The deleted message disappears from Inbox
* The messages of the last several days disappear from Inbox
* The delete message appears in the Trash folder
* No error in the UI
* Errors on the console:
```
Uncaught (in promise) Error: IMAP UID FETCH: Invalid uidset
    at IMAPFolder.runCommand (IMAPFolder.ts:88:15)
    at async IMAPFolder.fetchMessageList (IMAPFolder.ts:192:5)
    at async IMAPFolder.listNewMessages (IMAPFolder.ts:181:27)
    at async IMAPFolder.moveMessagesHere (IMAPFolder.ts:523:5)
    at async IMAPFolder.moveMessageHere (Folder.ts:113:5)
```

```
IMAP fetch    uid: "undefined:*"
```

Expected result:
* The deleted message disappears from Inbox
* No other messages disappear from Inbox
* The delete message appears in the Trash folder
* No errors in UI nor console

Cause:
* In the given situation, the getter `highestUID` returns `undefined` (it's unclear to me why), which leads to a bad IMAP fetch command.
* I am not sure whether the disappearing messages are also caused by this bug or another one.

**Comment by benbucksch** [comment]
I've pushed a hotfix that fixes the symptom, but not the cause.

**Comment by benbucksch** [comment]
> I am not sure whether the disappearing messages are also caused by this bug or another one.

I've filed separate bug #189 about that.

**Comment by benbucksch** [comment]
This was fixed by the locks in git commit 74267993
