### ISSUE TITLE
OWA: Login failing in the background

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#213]
**Reproduction**

1. Setup a `@outlook.com` account in Mustang with the `OWA` protocol
2. Click next

**Actual Result**

1. Login fails in the background
2. Console has error

**Expected Result**

1. No login failure in the background
2. Console has no error

**Stack**
```json
{
    "id": 1241,
    "success": false,
    "message": "Unexpected end of JSON input",
    "backendStack": "SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at parseJSONFromBytes (node:internal/deps/undici/undici:5472:19)\n    at successSteps (node:internal/deps/undici/undici:5454:27)\n    at fullyReadBody (node:internal/deps/undici/undici:4381:9)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async consumeBody (node:internal/deps/undici/undici:5463:7)\n    at async fetchJSON (file:///Users/jeremyc/Documents/GitHub/mustang/e2/out/main/index.js:126465:17)\n    at async JPCWebSocket.callListener (file:///Users/jeremyc/Documents/GitHub/mustang/e2/out/main/index.js:46167:16)\n    at async WSCall._incomingMessage (file:///Users/jeremyc/Documents/GitHub/mustang/e2/out/main/index.js:45750:20)\n    at async WebSocket.<anonymous> (file:///Users/jeremyc/Documents/GitHub/mustang/e2/out/main/index.js:45844:9)",
    "originalCall": {
        "id": 1241,
        "path": "call",
        "arg": {
            "obj": "38016196030746509312",
            "args": [
                "persist:login:account51",
                "https://outlook.live.com/owa/0/ev.owa2?ns=PendingRequest&ev=FinishNotificationRequest&UA=0"
            ]
        }
    }
}
```
**Console Error**
```
Error: Unexpected end of JSON input
    at message.js:153:16
    at new Promise (<anonymous>)
    at WSCall.makeCall (message.js:148:12)
    at JPCWebSocket.callRemote (protocol.js:161:31)
    at Object.fetchJSON (obj.js:198:55)
    at OWAAccount.listenForEvents (OWAAccount.ts:234:52)
    at OWAAccount.login (OWAAccount.ts:120:10)
    at async OWAAccount.verifyLogin (Account.ts:66:5)
    at async checkConfig (checkConfig.ts:8:5)
    at async CheckConfig.svelte:19:3
```

**Comment by benbucksch** [comment]
I see the same

**Comment by jermy-c** [comment]
This also produces `Cannot read properties of null (reading 'ParentFolder')` error, mentioned in https://github.com/mustang-im/mustang/issues/198#issuecomment-2354100068

**Reproduction**

1.  Setup a @outlook.com account in Mustang with the OWA protocol
2.  Click next

**Actual Result**

1. Error shows in the UI
2. You can click next and it is as if there was no error

<img width="588" alt="圖片" src="https://github.com/user-attachments/assets/bf3bc18d-dd0d-4194-9229-c2ad42c813fe">

**Comment by jermy-c** [comment]
**Error: Unexpected end of JSON input**

The response `OWAAccount.listenForEvents` from the fetch request is a body that is empty and `reponse.json()` from `fetchJSON()` is trying to parse an empty string.

**Comment by jermy-c** [comment]
Ocassionally `findFolders.Body.ResponseMessages.Items[0]` is:
```json
{
    "__type": "FindFolderResponseMessage:#Exchange",
    "RootFolder": null,
    "MessageText": "Too many concurrent connections opened., Cannot open mailbox. Server = BLAPR06MB6804.namprd06.prod.outlook.com, mdbGuid = 5e4a2f79-001e-4ea5-8c24-2bcb92742c95, maiboxGuid = 0003bffe-84b6-c7f5-0000-000000000000",
    "ResponseCode": "ErrorTooManyObjectsOpened",
    "ResponseClass": "Error"
}
```
causing the `Cannot read properties of null (reading 'ParentFolder')` error which means it might be a different issue. 

**Possible solutions:**

1. Check if the `RootFolder` is null and call `listFolder()` after a 1 sec delay
2. Check if there's too many connections to the server

**Comment by NeilRashbrook** [comment]
We have checks for too many connections in #159... but unfortunately those checks didn't apply to the session data call, so I rebased the branch and added the extra checking.
