### ISSUE TITLE
Store: Attachments: undefined (reading 'replace')

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#277]
**Reproduction**

1. Login to an EWS account
2. Click the small download icon for account
3. Click the small download icon for Inbox
4. Open folder properties for Inbox
5. Click `Download all messages`
6. Keep folder properties open
7. Click the small download icon for another folder
8. Click `Download all messages` for that folder, if not disable or grayed out
9. Repeat step 7 & 8 for each folder

**Actual Result**

1. Yellow error banner at the top showing `Cannot read properties of undefined (reading 'replace')`
2. Sometimes it only appears in the console
3. Seems to throw this error also `Error: EACCES: permission denied, open '[filename]'` sometimes

**Expected Result**

1. No Error

**Stack**
```
error.ts:14 TypeError: Cannot read properties of undefined (reading 'replace')
    at RawFilesAttachment.getDirPath (RawFilesAttachment.ts:87:80)
    at RawFilesAttachment.emailFinished (RawFilesAttachment.ts:37:26)
    at RawFilesAttachment.save (RawFilesAttachment.ts:17:32)
    at async Promise.allSettled (:5454/index 2)
    at async PromiseAllDone.wait (PromiseAllDone.ts:20:19)
    at async EWSEMail.saveCompleteMessage (EMail.ts:302:5)
    at async EWSFolder.downloadMessages (EWSFolder.ts:326:13)
    at async EWSFolder.downloadAllMessages (Folder.ts:100:27)
    at async onDownloadAll (FolderGeneral.svelte:76:18)
    at async HTMLButtonElement.myOnClick (Button.svelte:68:16)
```

```
Error: EACCES: permission denied, open '/Users/jeremyc/Library/Mustang/files/email/[emailaddress]/34-from neil to ben/attachment-1-0.calendar'
    at async Object.open (node:internal/fs/promises:639:25)
    at async writeFile (file:///Users/jeremyc/Documents/GitHub/mustang/e2/out/main/index.js:126607:20)
    at async JPCWebSocket.callListener (file:///Users/jeremyc/Documents/GitHub/mustang/e2/out/main/index.js:46167:16)
    at async WSCall._incomingMessage (file:///Users/jeremyc/Documents/GitHub/mustang/e2/out/main/index.js:45750:20)
    at async WebSocket.<anonymous> (file:///Users/jeremyc/Documents/GitHub/mustang/e2/out/main/index.js:45844:9) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/Users/jeremyc/Library/Mustang/files/email/neil-beonex.onmicrosoft.com/34-from neil to ben/attachment-1-0.calendar'
}
```

**Comment by jermy-c** [comment]
Also happens for OWA.

**Comment by benbucksch** [comment]
> Repeat step 7 & 8 for each folder

If I follow the steps, with all folders, I get a "Server cannot service this request right now", i.e. I run into throttling. I did eventually see the problem, but to reproduce it at will, and to to repeated tests, I'd like to know what exactly is causing it.

Can you please be more specific about which folder is causing the problem?

**Comment by benbucksch** [comment]
@jermy-c I think I fixed it. At least I don't see the error anymore. Without the fix, I saw the error eventually. With the fix, I don't see the error anymore.

Could you please re-test with master?
