### ISSUE TITLE
SQLFolder: UNIQUE constraint failed: folder.accountID, folder.path

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#279]
**Reproduction**

1. Login to an EWS account
2. Click the small download icon for account
3. Click the small download icon for Inbox
4. Click the small download icon for Sent folder

**Actual Result**

1. Yellow error banner at the top with `UNIQUE constraint failed: folder.accountID, folder.path`

**Expected**

1. No error

**Stack**
```
error.ts:6 Error: UNIQUE constraint failed: folder.accountID, folder.path
    at message.js:153:16
    at new Promise (<anonymous>)
    at WSCall.makeCall (message.js:148:12)
    at JPCWebSocket.callRemote (protocol.js:161:31)
    at RemoteClass.run (obj.js:225:55)
    at SQLFolder.save (SQLFolder.ts:27:48)
    at async SQLMailStorage.saveFolder (SQLMailStorage.ts:22:5)
    at async EWSFolder.save (Folder.ts:171:5)
    at async EWSFolder.readFolder (Folder.ts:58:7)
    at async EWSFolder.listMessages (EWSFolder.ts:43:5)
```

**Comment by benbucksch** [comment]
I have used EWS accounts, just now for testing the other bugs, but never seen this error.
Assigning to you, to either find a reliable reproduction, or a code fix.

**Comment by benbucksch** [comment]
@jermy-c You said that you don't see this anymore. Please re-open this issue, if you do.
