### ISSUE TITLE
IMAP: Mailbox doesn't exist

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#284]
**Reproduction**

1. Do a fresh login of an IMAP account
2. Click the small download icon on any folder with sub-folders shortly after logging in

**Actual Result**

1. Yellow banner at the top with `Mailbox doesn't exist: [folder]` or similar

**Expected Result**

1. No error

**Stack**

```
error.ts:6 IMAPCommandError: Mailbox doesn't exist: Mailspring
    at IMAPFolder.runCommand (IMAPFolder.ts:86:15)
    at async IMAPFolder.fetchUIDList (IMAPFolder.ts:262:5)
    at async IMAPFolder.checkDeletedMessages (IMAPFolder.ts:443:22)
    at async IMAPFolder.getNewMessages (IMAPFolder.ts:281:5)
    at async getMail (GetMailButton.svelte:55:16)
    at async catchErrors (error.ts:60:5)
```

```
error.ts:6 IMAPCommandError: Unknown Mailbox: [Gmail] (now in authenticated state) (Failure)
    at IMAPFolder.runCommand (IMAPFolder.ts:86:15)
    at async IMAPFolder.fetchUIDList (IMAPFolder.ts:262:5)
    at async IMAPFolder.checkDeletedMessages (IMAPFolder.ts:443:22)
    at async IMAPFolder.getNewMessages (IMAPFolder.ts:281:5)
    at async getMail (GetMailButton.svelte:55:16)
    at async catchErrors (error.ts:60:5)
```

**Comment by benbucksch** [comment]
The Mailspring folder is that existed on the ***@***.*** account, but I had deleted it,  using Mustang. Maybe it was only half deleted. Maybe it's in the list of subscriped folders,  but actually deleted, and Dovecot returns the list of subscribed folders when we ask for the folder list. I'll have to investigate this.

The [Gmail] folder is a special folder for Gmail, so it's a special case. Thunderbird has special handling for it. Can you find a separate bug about the [Gmail] folder, please?
-- 
Sent from my phone. Please excuse the brevity.

**Comment by benbucksch** [comment]
This might be due to SUBSCRIBED vs LISTED folders in IMAP.

**Comment by benbucksch** [comment]
Compare #594
