### ISSUE TITLE
ActiveSync: Mail: Error Sync status 12

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#293]
### Reproduction
* Set up EWS account neil@
* Don't use it for a while
* Open Inbox

### Actual result
* Error "ActiveSync Sync status 12"
* Stack

![image](https://github.com/user-attachments/assets/e4642de8-fbfe-4032-9ecc-2bcea2b3797c)

### Expected result
* No error, or:
* Human-readable, translated error message with cause, reason, and suggestion how to solve the problem.

**Comment by benbucksch** [comment]
@NeilRashbrook Can you please?
* Handle the errors that we can recover from.
* Show human-readable, translated error messages for all other sync codes that we cannot handle. We should never show "Sync status 12" and so on.

**Comment by benbucksch** [comment]
Comapre #223

**Comment by NeilRashbrook** [comment]
Sync status 12 means folder hierarchy resync required. This may end up deleting the folder we were trying to sync. How do you want to handle that case?

**Comment by benbucksch** [comment]
If the folder was deleted from the server, then there's not much we can do about it. Delete it locally. If it's the active folder, then the selected folder changes to inbox.

We can make a preference where we deliberately ignore all delete operations frpm the server, so that it works like POP3. But that won't be the default.

**Comment by benbucksch** [comment]
I am still seeing this

error.ts:6 ActiveSyncError: Neil ActiveSync: Folder hierarchy changed
    at ActiveSyncAccount.callEAS (ActiveSyncAccount.ts:279:13)
    at async ActiveSyncFolder.makeSyncRequest (ActiveSyncFolder.ts:111:20)
    at async ActiveSyncFolder.listMessages (ActiveSyncFolder.ts:146:5)
    at async loadFolder (MailApp.svelte:40:28)
