### ISSUE TITLE
cannot start a transaction within a transaction

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#297]
Directly after ermail account setup, possibly after changing folders:
```
Error
at file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:290387:16
at new Promise (<anonymous>)
at WSCall.makeCall (file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:290382:12)
at JPCWebSocket.callRemote (file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:293045:31)
at [RemoteClass.run](http://remoteclass.run/) (file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:292409:57)
at SQLEMail.saveMultiple (file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:94347:37)
at async SQLMailStorage.saveMessages (file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:94813:5)
at async IMAPFolder.saveNewMsgs (file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:71295:5)
at async IMAPFolder.listAllUnknownMessages (file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:71085:7)
at async IMAPFolder.listMessages (file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:71059:19)
at async loadFolder (file:///Applications/Mustang.app/Contents/Resources/app.asar/out/renderer/assets/index-q5RQlp59.js:397301:7)
```

**Comment by benbucksch** [comment]
@jermy-c There's already a lock around the `SQLEMail.sameMultiple()`. So, I don't know why it runs multiple times in parallel. Can you take a look, please, what is going on?

**Comment by benbucksch** [comment]
I found a potential cause for this problem and commited a fix in git commit fb851498.

@jermy-c : If you see this error messsage again (in master after this fix, or in upcoming release 0.7.4), could you please reopen this issue?

**Comment by benbucksch** [comment]
I've just got many errors of:
"Server event about folder INBOX failed: cannot start a transaction within a transaction mail.beonex.com IMAP server"
after Mustang was sitting there on the inbox, while I used another email client to read, delete and move emails from the inbox.
Stack at `IMAPAccount.ts:167:28`. This is the `"exists"` -> `countChanged()` event handler

I also got numerous errors of:
"Error: cannot start a transaction within a transaction"
with Stack:
```
at _SQLEMail.saveMultiple (SQLEMail.ts:229:35)
    at async SQLMailStorage.saveMessages (SQLMailStorage.ts:49:5)
    at async IMAPFolder.saveNewMsgs (IMAPFolder.ts:381:5)
    at async IMAPFolder.listNewMessages (IMAPFolder.ts:195:7)
    at async IMAPFolder.getNewMessages (IMAPFolder.ts:283:19)
```

**Comment by benbucksch** [comment]
One possibility is to lock the database for **all** access when we start a transaction.
I've tried to implement that in branch `sql-lock`, but with this change, all other folders stay empty, presumably because there's a lock in place and it blocks the read operation. I don't know why the lock is not released.

**Comment by jermy-c** [comment]
Seems like `BEGIN IMMEDIATE` fixes the problem since it makes it commit the changes immediately.

**Comment by jermy-c** [comment]
I tried doing `BEGIN IMMEDIATE` instead of `BEGIN TRANSACTION`, it doesn't work.

**Comment by benbucksch** [comment]
Fixed by git commit e8f64bc1. Thanks @nix-universe !
