### ISSUE TITLE
Mail: NOT NULL Contraint failed: email.dateSent

### ISSUE THREAD

**Issue by elenaux** [mustang-im/mustang#303]
Steps:
Click 'All accounts'
'All messages'

Actual results: see pic
![image](https://github.com/user-attachments/assets/a28d0176-90e9-4437-9a81-cba3c764c303)

**Comment by benbucksch** [comment]
Should be fixed in git commit 07e9dbe8

**Comment by nix-universe** [comment]
The issue occurred with 0.7.10.
### Steps to Reproduce
Open the App. 
Select a gmail account.
Select a folder

### Actual Behaviour
error.ts:6 Error: NOT NULL constraint failed: email.dateSent
    at message.js:155:16
    at new Promise (<anonymous>)
    at WSCall.makeCall (message.js:150:12)
    at JPCWebSocket.callRemote (protocol.js:165:31)
    at RemoteClass.run (obj.js:240:55)
    at SQLEMail.save (SQLEMail.ts:42:48)
    at async SQLEMail.saveMultiple (SQLEMail.ts:234:15)
    at async SQLMailStorage.saveMessages (SQLMailStorage.ts:49:11)
    at async IMAPFolder.saveNewMsgs (IMAPFolder.ts:381:11)
    at async IMAPFolder.listAllUnknownMessages (IMAPFolder.ts:147:13)
    at async IMAPFolder.listMessages (IMAPFolder.ts:111:19)
    at async loadFolder (MailApp.svelte:40:28)

### Expected Behaviour
No Error

**Comment by benbucksch** [comment]
@nix-universe I think we talked about this bug in real time together. There is no normal way that this can happen, because we ensure that `this.sent` set right before we write it. That was the fix here: 07e9dbe8e0 , see above.

We concluded that the only possible explanation is a race condition.

Nonetheless, that would require that there is some place where `this.sent` is set to a null value, and that code is executed while we're trying to write. However, there is no such place. *Every* place that writes to `this.sent` also has a fallback to `new Date()` = current time.

Even more strange, the faulty code from the stack reads: `email.sent.getTime() / 1000`. If `email.sent` was null, `getTime()` would throw. So, `getTime()` would need to return 0. But I don't see why it would do that, because `new Date()` returns the current time, not epoch. I doubt that this is the problem.

Curious...

**Comment by NeilRashbrook** [comment]
Is is possible that `email.sent` could be set to an invalid Date? That would then return `NaN` from `getTime()`, which JSON.stringify turns into `null`.

**Comment by benbucksch** [comment]
Ah, yes! That could be it, indeed. Thanks for the idea!

It's quite likely that some rare emails have invalid Date: header values. That
would also explain why the problem is relatively rare.



If that's the problem, sanitize.date() should check for NaN, and return the
fallback value (2. parameter) in this case.

**Comment by benbucksch** [comment]
@NeilRashbrook Thanks, I was able to verify that indeed, the cause was a message with an invalid date in the `Date:` header. The msg list would show "Invalid date", but it would fail on save, for exactly the reason you said, that `getTime()` returns `NaN` in this case.

I fixed this in `sanitize.date()` and verified that it fixes the bug.

Thanks a lot, Neil!
