### ISSUE TITLE
IMAP: Server event about folder INBOX failed

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#323]
**Reproduction**

1. Setup new Gmail account
2. (not sure if it was because I deleted the account before this) 

**Actual Result**

1. Console error:
```
startup.ts:80 IMAPCommandError: Server event about folder INBOX failed:
FOREIGN KEY constraint failed
imap.gmail.com IMAP server
    at IMAPAccount.ts:168:28
    at async JPCWebSocket.callListener (obj.js:351:16)
    at async WSCall._incomingMessage (message.js:96:20)
    at async WSCall.js:17:9
```

**Expected**

1. No Error

**Comment by jermy-c** [comment]
I got bug #297 trying to reproduce it again.
