### ISSUE TITLE
Setup: id is not defined

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#324]
**Reproduction**

1. Setup mail account

**Actual Result**

1. console error

```
Account.ts:113  ReferenceError: id is not defined
    at eval (VM1120 logpoint:1:47)
    at findFreeAccountID (Account.ts:113:14)
    at new Account (Account.ts:45:15)
    at new MailAccount (MailAccount.ts:13:8)
    at new IMAPAccount (IMAPAccount.ts:27:5)
    at _newAccountForProtocol (MailAccounts.ts:21:12)
    at newAccountForProtocol (MailAccounts.ts:14:13)
    at readServer (readConfig.ts:81:17)
    at readConfigFromXML (readConfig.ts:32:20)
    at fetchConfigFromISPDB (fetchConfig.ts:35:10)
```

**Expected Result**

1. No error

**Comment by jermy-c** [comment]
Sorry this was my debugger.
