### ISSUE TITLE
JPC: Local ID not found; Unhandled promise rejection

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#61]
2 separate issues, which might be related:
* "Local object with ID ... is unknown here"
* UnhandledPromiseRejection (somewhere, we're missing an `await` or `try/catch`)

```
Error {
  "id": 47,
  "success": false,
  "message": "Local object with ID 73742007272437137408 is unknown here.",
  "stack": "Error: Local object with ID 73742007272437137408 is unknown here.\n    at assert (http://localhost:5454/@fs.../mustang/client/lib/jpc/util.js:7:11)\n    at JPCWebSocket.getLocalObject (http://localhost:5454/@fs.../mustang/client/lib/jpc/obj.js:661:5)\n    at JPCWebSocket.callListener (http://localhost:5454/@fs.../mustang/client/lib/jpc/obj.js:341:21)\n    at WSCall._incomingMessage (http://localhost:5454/@fs.../mustang/client/lib/jpc/message.js:96:26)\n    at http://localhost:5454/@fs.../mustang/client/lib/jpc-ws/WSCall.js:16:12\n    at WebSocket.<anonymous> (http://localhost:5454/@fs.../mustang/client/lib/jpc-ws/protocol.js:84:58)",
  "originalCall": {
    "id": 47,
    "path": "call",
    "arg": {
      "obj": "73742007272437137408",
      "args": []
    }
  }
}
Error {
  "id": 48,
  "success": false,
  "message": "Local object with ID 24283683456460570624 is unknown here.",
  "stack": "Error: Local object with ID 24283683456460570624 is unknown here.\n    at assert (http://localhost:5454/@fs.../mustang/client/lib/jpc/util.js:7:11)\n    at JPCWebSocket.getLocalObject (http://localhost:5454/@fs.../mustang/client/lib/jpc/obj.js:661:5)\n    at JPCWebSocket.callListener (http://localhost:5454/@fs.../mustang/client/lib/jpc/obj.js:341:21)\n    at WSCall._incomingMessage (http://localhost:5454/@fs.../mustang/client/lib/jpc/message.js:96:26)\n    at http://localhost:5454/@fs.../mustang/client/lib/jpc-ws/WSCall.js:16:12\n    at WebSocket.<anonymous> (http://localhost:5454/@fs.../mustang/client/lib/jpc-ws/protocol.js:84:58)",
  "originalCall": {
    "id": 48,
    "path": "call",
    "arg": {
      "obj": "24283683456460570624",
      "args": [
        {
          "idSender": "27642003464666697728",
          "className": "Error",
          "properties": {
            "stack": "Error: Local object with ID 73742007272437137408 is unknown here.\n    at assert (http://localhost:5454/@fs.../mustang/client/lib/jpc/util.js:7:11)\n    at JPCWebSocket.getLocalObject (http://localhost:5454/@fs.../mustang/client/lib/jpc/obj.js:661:5)\n    at JPCWebSocket.callListener (http://localhost:5454/@fs.../mustang/client/lib/jpc/obj.js:341:21)\n    at WSCall._incomingMessage (http://localhost:5454/@fs.../mustang/client/lib/jpc/message.js:96:26)\n    at http://localhost:5454/@fs.../mustang/client/lib/jpc-ws/WSCall.js:16:12\n    at WebSocket.<anonymous> (http://localhost:5454/@fs.../mustang/client/lib/jpc-ws/protocol.js:84:58)",
            "message": "Local object with ID 73742007272437137408 is unknown here."
          }
        }
      ]
    }
  }
}
(node:1852009) UnhandledPromiseRejectionWarning: Error: Local object with ID 24283683456460570624 is unknown here.
    at assert (http://localhost:5454/@fs.../mustang/client/lib/jpc/util.js:7:11)
    at JPCWebSocket.getLocalObject (http://localhost:5454/@fs.../mustang/client/lib/jpc/obj.js:661:5)
    at JPCWebSocket.callListener (http://localhost:5454/@fs.../mustang/client/lib/jpc/obj.js:341:21)
    at WSCall._incomingMessage (http://localhost:5454/@fs.../mustang/client/lib/jpc/message.js:96:26)
    at http://localhost:5454/@fs.../mustang/client/lib/jpc-ws/WSCall.js:16:12
    at WebSocket.<anonymous> (http://localhost:5454/@fs.../mustang/client/lib/jpc-ws/protocol.js:84:58)
(node:1852009) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
```

**Comment by benbucksch** [comment]
We now have code to re-connect from frontend to backend when the JPC connection disappears for some reason. But that's not the bug here. The bug here is the opposite.

This happens when we as developers change the UI code, and the frontend automatically reload the entiere page/app, and then the frontend makes a new connection to the backend. But the backend still holds on to the old listeners that the old frontend had added. The fix might be weak references, maybe?

Given that only developers will run into this, this bug does has very low priority.

**Comment by benbucksch** [comment]
Would this be a problem for Mac, where the window can be closed and reopened?

**Comment by NeilRashbrook** [comment]
Even worse, it tries to start up the backend again. On the other hand, perhaps we could shut down the backend cleanly when the user closes the window? Then it would also restart when the window is reopened. (Is there even a way to shut down the backend cleanly?)

**Comment by benbucksch** [comment]
Good idea
